version: '3'

services:
  app:
    image: app
    restart: always
    build: ./
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - 8000:8000
    command: sh -c 'npm i && npm run dev'
    networks:
      otus-net:
  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ../tmp/mongo-db:/data/db
    ports:
      - 7003:27017
    networks:
      otus-net:
networks:
  otus-net:
